### ISSUE TITLE
Add associated event to announcement creation form.

### ISSUE THREAD

**Issue by jvansant** [opus-tm/mvp-frontend#67]
It would be good to go ahead and get this in now- It will be a good exercise for me as I begin to grasp react.

**Comment by willda07** [comment]
We should discuss this one -- not sure if we want the event creator to be on the same page as the announcements or if it should be on the calendar.

**Comment by jvansant** [comment]
That is not quite what I meant. I'm thinking we should add the ability to
select which event is tied to the announcement when you create the
announcment.

**Comment by jvansant** [comment]
@willda07 I went ahead and added this feature in and pushed to the announcemnts_page branch. 
Lmk if it doesn't work or if you think we should do it differently. The calendar will still be on a seperate app. I just meant that I would implement the link to event feature in this branch.
