### ISSUE TITLE
Announcement table filtered by team automatically with url

### ISSUE THREAD

**Issue by jvansant** [opus-tm/mvp-frontend#69]
For use once team dashboard is set up. The user can click the link and it will automatically filter the announcements based on the team.

Ex: /announcements/team=test/
Loads table filtered to only test teams announcements

**Comment by willda07** [comment]
This won't be included in pull request 64. I'll need to do this type of enhancement for Announcements, Contacts, and Chat anyway, so that'll be in with the widgets PR later.
